/**
 * Business registry: Beauty & Wellness OS - 18 Approved Categories Only.
 * Data file is generated by: node scripts/build-business-registry.mjs
 */
import type { BusinessCategory } from '../store/AppContext';

/** When a profile has no nicheId, map template → primary industry group (customer filters). */
export const PRIMARY_INDUSTRY_GROUP: Record<BusinessCategory, string> = {
  men_salon: 'beauty',
  beauty_parlour: 'beauty',
  unisex_salon: 'beauty',
  spa: 'beauty',
  other: 'beauty',
};
import {
  ALL_BUSINESS_NICHE_ROWS,
  BUSINESS_REGISTRY_GROUPS,
  type BusinessNicheRow,
  type BusinessRegistryGroup,
} from './businessRegistry.data';

export type { BusinessNicheRow, BusinessRegistryGroup };

export { ALL_BUSINESS_NICHE_ROWS, BUSINESS_REGISTRY_GROUPS };

const byId = new Map<string, BusinessNicheRow>(
  ALL_BUSINESS_NICHE_ROWS.map((r) => [r.id, r])
);

export function getBusinessNicheById(id: string | null | undefined): BusinessNicheRow | undefined {
  if (!id) return undefined;
  return byId.get(id);
}

export function searchBusinessNiches(query: string): BusinessNicheRow[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_BUSINESS_NICHE_ROWS;
  return ALL_BUSINESS_NICHE_ROWS.filter(
    (r) =>
      r.label.toLowerCase().includes(q) ||
      r.labelHi.includes(query) ||
      r.id.toLowerCase().includes(q)
  );
}

export function getNichesForGroup(groupId: string): BusinessNicheRow[] {
  return ALL_BUSINESS_NICHE_ROWS.filter((r) => r.groupId === groupId);
}

/** Resolve Firestore industry section for filters (niche wins; else template fallback). */
export function getIndustryGroupIdForBusiness(
  businessType: BusinessCategory,
  nicheId?: string | null
): string {
  if (nicheId) {
    const n = getBusinessNicheById(nicheId);
    if (n) return n.groupId;
  }
  return PRIMARY_INDUSTRY_GROUP[businessType] || 'beauty';
}

/** Visual hint per template — maps to CSS / Framer variants (Beauty & Wellness only). */
export const PRIMARY_INDUSTRY_GROUP: Record<BusinessCategory, string> = {
  mens_salon: 'beauty',
  ladies_parlour: 'beauty',
  unisex_salon: 'beauty',
  spa_center: 'beauty',
  nail_studio: 'beauty',
  mehndi_artist: 'beauty',
  tattoo_studio: 'beauty',
  massage_therapy: 'beauty',
  acupuncture_clinic: 'beauty',
  makeup_artist: 'beauty',
  bridal_studio: 'beauty',
  threading_waxing: 'beauty',
  skincare_clinic: 'beauty',
  hair_transplant: 'beauty',
  laser_studio: 'beauty',
  ayurveda_beauty: 'beauty',
  slimming_studio: 'beauty',
  home_salon: 'beauty',
};

export type IndustryVisualStyle =
  | 'glass-neon'
  | 'glass-warm'
  | 'glass-luxury'
  | 'mesh-aurora'
  | 'clay-soft'
  | 'minimal-pro';

export function getVisualStyleForTemplate(t: BusinessCategory): IndustryVisualStyle {
  switch (t) {
    case 'mens_salon':
    case 'unisex_salon':
    case 'hair_transplant':
    case 'laser_studio':
      return 'glass-neon';
    case 'ladies_parlour':
    case 'makeup_artist':
    case 'bridal_studio':
    case 'threading_waxing':
    case 'mehndi_artist':
    case 'nail_studio':
    case 'home_salon':
      return 'glass-luxury';
    case 'spa_center':
    case 'massage_therapy':
    case 'acupuncture_clinic':
    case 'skincare_clinic':
    case 'ayurveda_beauty':
    case 'slimming_studio':
      return 'mesh-aurora';
    case 'tattoo_studio':
      return 'glass-neon';
    default:
      return 'mesh-aurora';
  }
}
